defaults:
  - model: BERT_NO_POOL
  - data: EN_MedRQE

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

tasks: [ "fit" ]

trainer:
  max_epochs: 4
  gpus: 1
  patience: 2
  min_delta: 0.05
  precision: 16
  fast_dev_run: False
  progress_bar_refresh_rate: 1
